### ISSUE TITLE
【5inch連装砲(副砲配置) 集中配備】について

### ISSUE THREAD

**Issue by h5nc** [madonoharu/fleethub#22]
いつもありがとうございます。

【5inch連装砲(副砲配置) 集中配備】について、
https://storage.googleapis.com/kcfleethub.appspot.com/data/master_data.json

{"gear_id":467,"types":[1,2,4,16,0],"name":"5inch連装砲(副砲配置) 集中配備","armor":1,"firepower":5,"anti_air":11,"accuracy":4,"evasion":3,"range":1}

と記載しているが、special_typeの情報が入っていません。
管理シートから見ても装備種95番は未登録の状態です。

そのため作戦室サイトでは、水上機母艦などでも、ゲーム中で装備できない艦種でも選択できるようになってしまいます。

テスト不十分かもしれないですが、
                "stypes": [
                    5,
                    8,
                    9,
                    10,
                    11,
                    18
                ],
の艦種の通常スロットのみ装備できるようです。

いつも作戦室を愛用しております。大変お手数ですが、管理シートなどの更新していただけると幸いです。
よろしくお願いいたします。

**Comment by madonoharu** [comment]
返信が遅くなりました
装備種95に対応しました
ありがとうございます！
