### ISSUE TITLE
Organization loading via url

### ISSUE THREAD

**Issue by myangelkamikaze** [MadonoHaru/fleethub#30]
The organization loading has a bug when using the [extended deckbuilder format](https://github.com/Nishisonic/gkcoi#usage). The usage example shows that the values are meant to be total stats, including equipment. But when you generate a link with full stats included, 作戦室 will add equipment stats on top of the total stats.

[Example ](https://jervis.vercel.app?predeck=%7B%22version%22%3A4%2C%22hqlv%22%3A120%2C%22f1%22%3A%7B%22name%22%3A%22%E5%A4%A7%E5%A4%A9%E4%BD%BF%E7%A5%9E%E9%A2%A8%E3%81%A1%E3%82%83%E3%82%93%22%2C%22s1%22%3A%7B%22id%22%3A476%2C%22lv%22%3A180%2C%22exa%22%3Atrue%2C%22items%22%3A%7B%22i1%22%3A%7B%22id%22%3A262%2C%22rf%22%3A3%7D%2C%22i2%22%3A%7B%22id%22%3A439%2C%22rf%22%3A0%7D%2C%22i3%22%3A%7B%22id%22%3A288%2C%22rf%22%3A2%7D%2C%22ix%22%3A%7B%22id%22%3A412%2C%22rf%22%3A8%7D%7D%2C%22hp%22%3A29%2C%22fp%22%3A44%2C%22tp%22%3A77%2C%22aa%22%3A49%2C%22ar%22%3A38%2C%22asw%22%3A180%2C%22ev%22%3A138%2C%22los%22%3A75%2C%22luck%22%3A99%2C%22sp%22%3A10%2C%22ra%22%3A2%7D%7D%2C%22a1%22%3A%7B%22name%22%3A%22%E7%AC%AC%E4%B8%80%E5%9F%BA%E5%9C%B0%E8%88%AA%E7%A9%BA%E9%9A%8A%22%2C%22items%22%3A%7B%22i1%22%3A%7B%22id%22%3A416%2C%22rf%22%3A4%2C%22mas%22%3A7%7D%2C%22i2%22%3A%7B%22id%22%3A454%2C%22rf%22%3A0%2C%22mas%22%3A7%7D%2C%22i3%22%3A%7B%22id%22%3A404%2C%22rf%22%3A0%2C%22mas%22%3A6%7D%2C%22i4%22%3A%7B%22id%22%3A270%2C%22rf%22%3A0%2C%22mas%22%3A7%7D%7D%2C%22mode%22%3A1%2C%22distance%22%3A3%7D%7D)

Expected: 
![image](https://github.com/madonoharu/fleethub/assets/40002167/8985afc7-0bf0-4ba9-8363-6f3bcf9b5d30)

Actual:
![image](https://github.com/madonoharu/fleethub/assets/40002167/0389efca-ca40-4345-8d46-366927efcc67)

Note that this doesn't happen for all stats. The torpedo stat behaves normally, but anti-submarine gets an incorrect value.

**Comment by madonoharu** [comment]
Thanks👍

**Comment by myangelkamikaze** [comment]
Thanks for the fix!
